import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import dynamic from "next/dynamic";
import { Col, Grid, Row } from "antd";
const inter = Inter({ subsets: ["latin"] });
const ShopLayout = dynamic(() => import("../../components/ShopLayout"));
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  todo,
  notifications,
}: Readonly<{
  children: React.ReactNode;
  todo: React.ReactNode;
  notifications: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AntdRegistry>
          <ShopLayout user={{}}>
            <Row>
              <Col span={16}>{todo}</Col>
              <Col span={8}>{notifications}</Col>
            </Row>
            {children}
          </ShopLayout>
        </AntdRegistry>
      </body>
    </html>
  );
}
